name: ${project.name}
author: [RiotSeb]
version: ${project.version}(${timestamp})
main: ${project.groupId}.${project.artifactId}.${project.name}
description: ${project.description}

permissions:
  AdventCalendar.edit:
    description: "Edit the AdventCalendar"